services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
